environment:
  - self-service-ai-application-platforms/demo-ai-idp-cluster-cluster
config:
  litellm-app-ecr:agentHomeSubPath: .home
  litellm-app-ecr:agentWorkspaceSize: 50Gi
  litellm-app-ecr:agentWorkspaceStorageClass: gp3
  litellm-app-ecr:litellmMasterKey:
    secure: AAABAEKRvBMg/hJqAx9OsjL5OLbKyPbKsHpbHRB3HNTxX8Ft9RrdZtS8G8MA7/idpl0F9gJpCDA+r9s=
  litellm-app-ecr:enableMaaSCloudFront: "true"
